// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swvuvewrsqvaixthhmzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dnV2ZXdyc3F2YWl4dGhobXppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDc1MjgsImV4cCI6MjA2NTcyMzUyOH0.lLeywSLX75zR7ysgvhpwDO8uH3Ohv0EdxfSyaKWZ_Gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);